### ISSUE TITLE
TypeError: Cannot read property 'mode' of undefined

### ISSUE THREAD

**Issue by Thespawn007** [loadimpact/postman-to-loadimpact#5]
Tried to use postman-to-loadimpact first time but when i started example command "postman-to-loadimpact examples/postman/v2/echo.json" i getting same error^ how to resolve this problem?
Full log:
TypeError: Cannot read property 'mode' of undefined
    at convertToLuaRequest (/usr/local/lib/node_modules/postman-to-loadimpact/lib/postman/lua-generator.js:182:28)
    at PostmanItemGroup.<anonymous> (/usr/local/lib/node_modules/postman-to-loadimpact/lib/postman/lua-generator.js:37:24)
    at /usr/local/lib/node_modules/postman-to-loadimpact/node_modules/lodash/index.js:2874:23
    at /usr/local/lib/node_modules/postman-to-loadimpact/node_modules/lodash/index.js:3049:15
    at Function.<anonymous> (/usr/local/lib/node_modules/postman-to-loadimpact/node_modules/lodash/index.js:3346:13)
    at PostmanPropertyList.each (/usr/local/lib/node_modules/postman-to-loadimpact/node_modules/postman-collection/lib/collection/property-list.js:199:11)
    at PostmanCollection.<anonymous> (/usr/local/lib/node_modules/postman-to-loadimpact/lib/postman/lua-generator.js:35:22)
    at /usr/local/lib/node_modules/postman-to-loadimpact/node_modules/lodash/index.js:2874:23
    at /usr/local/lib/node_modules/postman-to-loadimpact/node_modules/lodash/index.js:3049:15
    at Function.<anonymous> (/usr/local/lib/node_modules/postman-to-loadimpact/node_modules/lodash/index.js:3346:13)

**Comment by Thespawn007** [comment]
with version 1.0.0 convert works
